### ISSUE TITLE
Traduction en français ?

### ISSUE THREAD

**Issue by Mimoza** [ANSSI-FR/rust-guide#12]
Sachant que vous êtes une instance publique française, que la documentation en anglais est déjà suffisamment fournit pour ce langage, pourquoi ne pas rédiger ce document en français ?

Au minimum une traduction est elle prévue ?

**Comment by ad-anssi** [comment]
Étant donné que la plupart des communications autour du langage Rust sont faites
en langue anglaise, il nous paraît approprié de rédiger nous aussi ce guide en
anglais. Cela permet de rendre le document accessible au plus grand nombre, à
destination des utilisateurs de Rust dans leur ensemble.

Une traduction en français est envisagée pour les versions _release_ du guide.

**Comment by Mimoza** [comment]
Je comprend que vous ne vouliez pas vous privez de contribution notable avec la barrière de la langue.
Si un traduction est prévu ça me parait correct.
