### ISSUE TITLE
#[forbid(unsafe_code)] should be #![forbid(unsafe_code)]

### ISSUE THREAD

**Issue by bjorn3** [ANSSI-FR/rust-guide#41]
> With the exception of these cases, #[forbid(unsafe_code)] must appear in main.rs to generate compilation errors if unsafe is used in the code base.

`#[]` without `!` only applies to the item after it, not the item within which it is contained.

**Comment by bjorn3** [comment]
Just noticed #18.

**Comment by ad-anssi** [comment]
Well, this PR should have been merged a while ago... Thank you for reminding me.
