### ISSUE TITLE
Cargo-geiger for detection of unsafe blocks

### ISSUE THREAD

**Issue by Shadlock0133** [ANSSI-FR/rust-guide#9]
One can use [cargo-geiger](https://github.com/anderejd/cargo-geiger) to check for unsafe blocks in the crate and its dependencies.

**Comment by Harvester57** [comment]
It was already proposed in PR https://github.com/ANSSI-FR/rust-guide/pull/7 and https://github.com/ANSSI-FR/rust-guide/pull/5

**Comment by ad-anssi** [comment]
Thank you @Shadlock0133 for reporting this tool very soon. Closing this issue as the topic of `cargo-geiger` and `forbid[unsafe_code]` is discussed in details in #10 .
